#!/bin/bash

function Usage {
    echo "Usage:"
    echo "   $0 clean"
    echo "   $0 make"
    echo "   $0 flash"
    echo "   $0 mon"
    echo "   $0 flashmon"
    echo "   $0 flash-nvs"
    exit
}

ESP_DIR=$HOME/esp/esp-idf
EXPORT_SH=$ESP_DIR/export.sh

if [[ ":$PATH:" == *"$ESP_DIR/tools:"* ]]; then
    echo "ESP environment is already activated."
else
    echo "=============================================================="
    echo "ESP environment is not activated. Run . $EXPORT_SH in your shell."
    echo "=============================================================="
    . $EXPORT_SH
fi

PORT="/dev/ttyUSB0"
export IDF_TARGET=esp32
export COMPONENTS_PATH=$HOME/esp/components


function build {
    idf.py build
}

function flash {
    idf.py -p $PORT flash
}

function nvsflash {
    idf.py -p $PORT nvs-flash
}

function monitor {
    idf.py -p $PORT monitor -b 115200
}

if [[ "$#" == 0 ]]; then
    Usage
fi

if [[ "$1" == "clean" ]]; then
    idf.py fullclean
    exit
fi

if [[ "$1" == "make" ]]; then
    build "$@"
fi

if [[ "$1" == "flash" ]]; then
    flash
fi

if [[ "$1" == "mon" ]]; then
    monitor
fi

if [[ "$1" == "flash-nvs" ]]; then
    nvsflash
fi

if [[ "$1" == "flashmon" ]]; then
    flash && monitor
fi
